EMOJI_GOOD = '\U0001F44D'
EMOJI_BAD = '\U0001F44E'
EMOJI_2 = '2v2'
EMOJI_3 = '3v3'
EMOJI_4 = '4v4'
EMOJI_5 = '5v5'
BATTLE_ADMIN = 'admin'
BATTLE_COMMANDER = 'Battle Commander'
MATCH_COMMANDER = 'Match Commander'

BATTLE_EMOJI = {EMOJI_2: 2, EMOJI_3: 3, EMOJI_4: 4, EMOJI_5: 5}
AdministratorRoles = [BATTLE_ADMIN, BATTLE_COMMANDER]
OrganizerRoles = [BATTLE_ADMIN, BATTLE_COMMANDER]
ReporterRoles = [BATTLE_ADMIN, BATTLE_COMMANDER, MATCH_COMMANDER]
